name: "Linting-tool-Scan"

on: 
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt install npm
          sudo npm install --package-lock
          npm audit fix
      - name: Installing JSHint
        run: |
          sudo npm install -g jshint 
      
      - name: Run scan with JSHint
        run: script/jshint-script.sh

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Linting Tool Report
          path: |
            ./JSHint-report
